import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import { AppWrapper } from '../utils/context'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import('../components/Header'), {
  ssr: false,
})


export default function Layout({children, title}) {

  
  const{state, dispatch} = useContext(AppWrapper);
  const {cart}  = state;

  const [cartItemsCount, setCartItemsCount] = useState(0)


  useEffect(() => {
  
    // setCartItemsCount(cart.cartItem.reduce((a,c) => a + c.quantity }, 0) )
    setCartItemsCount(cart.cartItem.reduce((a,c) => a + c.quantity , 0));
    
  }, [cart.cartItem])
  
  return (
    <div className='flex  font-Poppins font-medium min-h-screen flex-col  justify-between '>

        <Head>
        <title >{title ? title : 'Wrong'} Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position='bottom-center' limit={1} />
      <DynamicHeader />
        <main>{children}</main>
        <footer className='h-16 text-xl border  flex font-Courgette font-light justify-center items-center  text-center'>
        <div>      
            Made with 💖  By &nbsp;&nbsp;
          <span className="before:block before:absolute before:-inset-1 before:-skew-y-6 before:bg-pink-500 relative inline-block">
               <span className="relative  text-white">Arun Kumar</span>
            </span>  
        </div>

         </footer>
    </div>
  )
}
