import React, { useContext, useEffect, useState } from 'react'
import {HiOutlineShoppingCart} from 'react-icons/hi'
import Head from 'next/head'
import { AppWrapper } from '../utils/context'
import Link from 'next/link';
export default function Layout({children, title}) {

  
  const{state, dispatch} = useContext(AppWrapper);
  const {cart}  = state;
  console.log(cart)

  const [cartItemsCount, setCartItemsCount] = useState(0)


  useEffect(() => {
  
    setCartItemsCount(cart.cartItem.reduce((a,c) =>{
      
     return  a + c.quantity }, 0) )
    
  }, [cart.cartItem])
  
  return (
    <div className='flex font-Poppins font-medium min-h-screen flex-col  justify-between '>

        <Head>
        <title >{title ? title : 'Wrong'} Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <nav className='text-xl p-6 h-16 border shadow-inner flex items-center justify-between '>
          <Link href="/">
          <div className='cursor-pointer'>
            Company 
          </div>
          </Link>
          



          <div className=" flex items-center  w-20 justify-between">
            
          <div className='relative '>
          <HiOutlineShoppingCart className='text-3xl  font-light text-[#070932]  cursor-pointer'>

          </HiOutlineShoppingCart>

          {cartItemsCount > 0 && (
            <span className='ml-1 absolute text-xs top-0 right-[-4px] rounded-full bg-blue-gray-100 px-1 font-medium '>
              {cartItemsCount}
             
            </span>
          )}
           {console.log(cartItemsCount)}
          </div>
  
</div>
          
         
        
        </nav>
        <main>{children}</main>
        <footer className='h-16 text-xl border  flex font-Courgette font-light justify-center items-center  text-center'>
        <div>
            
            Made with 💖  By &nbsp;&nbsp;
          <span className="before:block before:absolute before:-inset-1 before:-skew-y-6 before:bg-pink-500 relative inline-block">
               <span className="relative  text-white">Arun Kumar</span>
            </span>
          
          
        </div>

         </footer>
    </div>
  )
}
