import React, { useContext, useEffect, useState } from 'react'

import Head from 'next/head'
import { AppWrapper } from '../utils/context'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import Link from 'next/link';


import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import('../components/Header'), {
  ssr: false,
})


export default function Layout({children, title}) {

  
  const{state, dispatch} = useContext(AppWrapper);
  const {cart}  = state;
  // {console.log(cart)}

  const [cartItemsCount, setCartItemsCount] = useState(0)


  useEffect(() => {
  
    // setCartItemsCount(cart.cartItem.reduce((a,c) => a + c.quantity }, 0) )
    setCartItemsCount(cart.cartItem.reduce((a,c) => a + c.quantity , 0));
    
  }, [cart.cartItem])
  
  return (
    <div className='flex  font-Poppins font-medium min-h-screen flex-col  justify-between '>

        <Head>
        <title >{title ? title : 'Wrong'} Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <ToastContainer position='bottom-center' limit={1} />


      <DynamicHeader />
      {/* <Header/> */}
      {/* <div>
          <header>
          <nav className='text-xl p-6 h-16 sticky border shadow-inner flex items-center justify-between '>
            <Link href="/">
            <a className='cursor-pointer'>
              Company 
            </a>
            </Link>
            
        
        
        
            <div className=" flex items-center  w-20 justify-between">
              
            <div className='relative '>
     
        
        
{/* 
          
              {cart.cartItem.length > 0 && (
                <span className='ml-1 absolute text-xs top-0 right-[-4px] rounded-full bg-blue-gray-100 px-1 font-medium '>
                  {cart.cartItem.reduce((a,c) => a + c.quantity, 0)}
                
                </span>
              )} */}
 
                {/* <div>
                <HiOutlineShoppingCart className="text-3xl"/>
                </div> */}

  {/* {cart.cartItem.length  > 0 && (
    <span className='ml-1 absolute text-xs top-0 right-[-4px] rounded-full bg-blue-gray-100 px-1 font-medium'>
      {cartItemsCount}
    </span>
  )} */}



{/*              
            </div>
            
        </div>
            
           
  
          </nav>
          </header>

      </div> */}



        <main>{children}</main>
        <footer className='h-16 text-xl border  flex font-Courgette font-light justify-center items-center  text-center'>
        <div>
            
            Made with 💖  By &nbsp;&nbsp;
          <span className="before:block before:absolute before:-inset-1 before:-skew-y-6 before:bg-pink-500 relative inline-block">
               <span className="relative  text-white">Arun Kumar</span>
            </span>
          
          
        </div>

         </footer>
    </div>
  )
}
